name 'application'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures application'
long_description 'Installs/Configures application'
version '0.1.0'

depends 'apache2'
depends 'mysql'
depends 'php'
